# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ShortCutDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShortCutDialog(object):
    def setupUi(self, ShortCutDialog):
        ShortCutDialog.setObjectName("ShortCutDialog")
        ShortCutDialog.resize(689, 620)
        ShortCutDialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 35, 45);\n"
"font: 9pt \"微软雅黑\";")
        self.verticalLayout = QtWidgets.QVBoxLayout(ShortCutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ShortCutFrame = QtWidgets.QFrame(ShortCutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShortCutFrame.sizePolicy().hasHeightForWidth())
        self.ShortCutFrame.setSizePolicy(sizePolicy)
        self.ShortCutFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.ShortCutFrame.setStyleSheet("QFrame#ShortCutFrame{\n"
"    border: 1px solid rgb(70,80,100);\n"
"}")
        self.ShortCutFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ShortCutFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ShortCutFrame.setObjectName("ShortCutFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ShortCutFrame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.ShortCutFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_2.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.View_groupBox = QtWidgets.QGroupBox(self.page)
        self.View_groupBox.setStyleSheet("QGroupBox#View_groupBox\n"
"{\n"
"    border: 1px solid rgb(70,80,100);\n"
"    margin-top: 3.0ex;\n"
"}\n"
"QGroupBox#View_groupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.View_groupBox.setObjectName("View_groupBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.View_groupBox)
        self.verticalLayout_7.setContentsMargins(6, 10, 6, 6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(6, 6, 6, 6)
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(9)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_7.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 290, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.textBrowser = QtWidgets.QTextBrowser(self.View_groupBox)
        self.textBrowser.setStyleSheet("QTextBrowser#textBrowser{\n"
"    border: 1px solid rgb(70,80,100);\n"
"}")
        self.textBrowser.setTabStopWidth(80)
        self.textBrowser.setCursorWidth(1)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_7.addWidget(self.textBrowser)
        self.verticalLayout_2.addWidget(self.View_groupBox)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setContentsMargins(6, 0, 6, 6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Fun_groupBox = QtWidgets.QGroupBox(self.page_2)
        self.Fun_groupBox.setStyleSheet("QGroupBox#Fun_groupBox\n"
"{\n"
"    border: 1px solid rgb(70,80,100);\n"
"    margin-top: 3.0ex;\n"
"}\n"
"QGroupBox#Fun_groupBox::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.Fun_groupBox.setObjectName("Fun_groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Fun_groupBox)
        self.verticalLayout_9.setContentsMargins(6, 10, 6, 6)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.shortcut_gridLayout = QtWidgets.QGridLayout()
        self.shortcut_gridLayout.setContentsMargins(6, 6, 6, 6)
        self.shortcut_gridLayout.setHorizontalSpacing(18)
        self.shortcut_gridLayout.setVerticalSpacing(6)
        self.shortcut_gridLayout.setObjectName("shortcut_gridLayout")
        self.verticalLayout_9.addLayout(self.shortcut_gridLayout)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.Fun_groupBox)
        self.textBrowser_2.setStyleSheet("QTextBrowser#textBrowser_2{\n"
"    border: 1px solid rgb(70,80,100);\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_9.addWidget(self.textBrowser_2)
        self.verticalLayout_8.addWidget(self.Fun_groupBox)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.ShortCutFrame)
        self.ButtonFrame = QtWidgets.QFrame(ShortCutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ButtonFrame.sizePolicy().hasHeightForWidth())
        self.ButtonFrame.setSizePolicy(sizePolicy)
        self.ButtonFrame.setMinimumSize(QtCore.QSize(160, 0))
        self.ButtonFrame.setStyleSheet("QFrame#ButtonFrame{\n"
"    border: 1px solid rgb(70,80,100);\n"
"}")
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.ButtonFrame)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.ButtonFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(50, 0))
        self.listWidget.setStyleSheet("QListWidget#listWidget{\n"
"    border: 1px solid rgb(70,80,100);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.RestoreKeybindingsButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.RestoreKeybindingsButton.setObjectName("RestoreKeybindingsButton")
        self.verticalLayout_3.addWidget(self.RestoreKeybindingsButton)
        self.CancelButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.CancelButton.setObjectName("CancelButton")
        self.verticalLayout_3.addWidget(self.CancelButton)
        self.OkButton = QtWidgets.QPushButton(self.ButtonFrame)
        self.OkButton.setObjectName("OkButton")
        self.verticalLayout_3.addWidget(self.OkButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.ButtonFrame)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ShortCutDialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ShortCutDialog)

    def retranslateUi(self, ShortCutDialog):
        _translate = QtCore.QCoreApplication.translate
        ShortCutDialog.setWindowTitle(_translate("ShortCutDialog", "ShortCutDialog"))
        self.View_groupBox.setTitle(_translate("ShortCutDialog", "Mouse Shortcuts"))
        self.textBrowser.setHtml(_translate("ShortCutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ff0000;\">Red mark</span> indicates selected mark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#0059ff;\">Blue mark</span> indicates non-special mark</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#37ff00;\">Green mark</span> indicates edge mark</p></body></html>"))
        self.Fun_groupBox.setTitle(_translate("ShortCutDialog", "Keyboard Shortcuts"))
        self.textBrowser_2.setHtml(_translate("ShortCutDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Click the button under <span style=\" color:#ffcf0f;\">Keybinding</span>, edit the text under <span style=\" color:#ffcf0f;\">Edit</span> (by pressing a key and then Enter) to modify the shortcut, and click <span style=\" color:#ffcf0f;\">OK</span> to complete the modification.</p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("ShortCutDialog", "Mouse Shortcuts"))
        item = self.listWidget.item(1)
        item.setText(_translate("ShortCutDialog", "Keyboard Shortcuts"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.RestoreKeybindingsButton.setText(_translate("ShortCutDialog", "Restore Default"))
        self.CancelButton.setText(_translate("ShortCutDialog", "Cancel"))
        self.OkButton.setText(_translate("ShortCutDialog", "OK"))
