# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_NoMenubarWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoMenubarWidget(object):
    def setupUi_win(self, NoMenubarWidget):
        NoMenubarWidget.setObjectName("NoMenubarWidget")
        NoMenubarWidget.resize(1200, 880)
        NoMenubarWidget.setStyleSheet("font: 9pt \"微软雅黑\";")
        self.centralwidget = QtWidgets.QWidget(NoMenubarWidget)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.central_hbox = QtWidgets.QHBoxLayout(self.centralwidget)
        self.central_hbox.setContentsMargins(0, 0, 0, 0)
        self.central_hbox.setObjectName("central_hbox")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("")
        self.frame.setObjectName("frame")
        self.frame_hbox = QtWidgets.QHBoxLayout(self.frame)
        self.frame_hbox.setContentsMargins(0, 0, 0, 0)
        self.frame_hbox.setSpacing(6)
        self.frame_hbox.setObjectName("frame_hbox")
        self.frame_vl = QtWidgets.QVBoxLayout()
        self.frame_vl.setContentsMargins(0, -1, -1, -1)
        self.frame_vl.setSpacing(6)
        self.frame_vl.setObjectName("frame_vl")
        self.frame_hbox.addLayout(self.frame_vl)
        self.central_hbox.addWidget(self.frame)
        NoMenubarWidget.setCentralWidget(self.centralwidget)
        self.myStatus = QtWidgets.QStatusBar(NoMenubarWidget)
        self.myStatus.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";")
        self.myStatus.setObjectName("myStatus")
        NoMenubarWidget.setStatusBar(self.myStatus)

        self.retranslateUi_win(NoMenubarWidget)
        QtCore.QMetaObject.connectSlotsByName(NoMenubarWidget)

    def retranslateUi_win(self, NoMenubarWidget):
        _translate = QtCore.QCoreApplication.translate
        NoMenubarWidget.setWindowTitle(_translate("NoMenubarWidget", "CellPointsMarking"))
