# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_branch_select_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_branch_select_Form(object):
    def setupUi(self, branch_select_Form):
        branch_select_Form.setObjectName("branch_select_Form")
        branch_select_Form.setWindowModality(QtCore.Qt.WindowModal)
        branch_select_Form.resize(378, 211)
        branch_select_Form.setMaximumSize(QtCore.QSize(16777215, 500))
        branch_select_Form.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";\n"
"")
        self.branch_select_Form_hbox = QtWidgets.QHBoxLayout(branch_select_Form)
        self.branch_select_Form_hbox.setObjectName("branch_select_Form_hbox")
        self.bs_vbox = QtWidgets.QVBoxLayout()
        self.bs_vbox.setObjectName("bs_vbox")
        self.branch_select_hbox = QtWidgets.QHBoxLayout()
        self.branch_select_hbox.setObjectName("branch_select_hbox")
        self.branch_select_label = QtWidgets.QLabel(branch_select_Form)
        self.branch_select_label.setObjectName("branch_select_label")
        self.branch_select_hbox.addWidget(self.branch_select_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.branch_select_hbox.addItem(spacerItem)
        self.bs_vbox.addLayout(self.branch_select_hbox)
        self.branch_select_listwidget = QtWidgets.QListWidget(branch_select_Form)
        self.branch_select_listwidget.setStyleSheet("")
        self.branch_select_listwidget.setObjectName("branch_select_listwidget")
        self.bs_vbox.addWidget(self.branch_select_listwidget)
        self.branch_select_button_hbox = QtWidgets.QHBoxLayout()
        self.branch_select_button_hbox.setObjectName("branch_select_button_hbox")
        self.branch_forward_Button = QtWidgets.QPushButton(branch_select_Form)
        self.branch_forward_Button.setObjectName("branch_forward_Button")
        self.branch_select_button_hbox.addWidget(self.branch_forward_Button)
        self.branch_backward_Button = QtWidgets.QPushButton(branch_select_Form)
        self.branch_backward_Button.setObjectName("branch_backward_Button")
        self.branch_select_button_hbox.addWidget(self.branch_backward_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.branch_select_button_hbox.addItem(spacerItem1)
        self.branch_sure_button = QtWidgets.QPushButton(branch_select_Form)
        self.branch_sure_button.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"color: rgb(255, 255, 255);")
        self.branch_sure_button.setObjectName("branch_sure_button")
        self.branch_select_button_hbox.addWidget(self.branch_sure_button)
        self.branch_close_button = QtWidgets.QPushButton(branch_select_Form)
        self.branch_close_button.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"color: rgb(255, 255, 255);")
        self.branch_close_button.setObjectName("branch_close_button")
        self.branch_select_button_hbox.addWidget(self.branch_close_button)
        self.bs_vbox.addLayout(self.branch_select_button_hbox)
        self.branch_select_Form_hbox.addLayout(self.bs_vbox)

        self.retranslateUi(branch_select_Form)
        QtCore.QMetaObject.connectSlotsByName(branch_select_Form)

    def retranslateUi(self, branch_select_Form):
        _translate = QtCore.QCoreApplication.translate
        branch_select_Form.setWindowTitle(_translate("branch_select_Form", "BranchSelectWidget"))
        self.branch_select_label.setText(_translate("branch_select_Form", "node select"))
        self.branch_forward_Button.setText(_translate("branch_select_Form", "previous"))
        self.branch_backward_Button.setText(_translate("branch_select_Form", "next"))
        self.branch_sure_button.setText(_translate("branch_select_Form", "ok"))
        self.branch_close_button.setText(_translate("branch_select_Form", "cancel"))
