# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_xyz_px_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_xyz_px_dialog(object):
    def setupUi(self, xyz_px_dialog):
        xyz_px_dialog.setObjectName("xyz_px_dialog")
        xyz_px_dialog.resize(279, 153)
        xyz_px_dialog.setStyleSheet("background-color: rgb(25, 35, 45);\n"
"font: 9pt \"微软雅黑\";\n"
"color: rgb(255, 255, 255);")
        self.xyz_px_dialog_hbox = QtWidgets.QHBoxLayout(xyz_px_dialog)
        self.xyz_px_dialog_hbox.setObjectName("xyz_px_dialog_hbox")
        self.xyz_vbox = QtWidgets.QVBoxLayout()
        self.xyz_vbox.setObjectName("xyz_vbox")
        self.xyz_groupbox = QtWidgets.QGroupBox(xyz_px_dialog)
        self.xyz_groupbox.setStyleSheet("font: 9pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.xyz_groupbox.setTitle("")
        self.xyz_groupbox.setObjectName("xyz_groupbox")
        self.xyz_groupbox_hbox = QtWidgets.QHBoxLayout(self.xyz_groupbox)
        self.xyz_groupbox_hbox.setObjectName("xyz_groupbox_hbox")
        self.groupbox_vbox = QtWidgets.QVBoxLayout()
        self.groupbox_vbox.setObjectName("groupbox_vbox")
        self.x_form = QtWidgets.QFormLayout()
        self.x_form.setObjectName("x_form")
        self.x_px_label = QtWidgets.QLabel(self.xyz_groupbox)
        self.x_px_label.setMouseTracking(False)
        self.x_px_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.x_px_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";")
        self.x_px_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.x_px_label.setTextFormat(QtCore.Qt.AutoText)
        self.x_px_label.setScaledContents(False)
        self.x_px_label.setObjectName("x_px_label")
        self.x_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.x_px_label)
        self.x_px_spinbox = QtWidgets.QDoubleSpinBox(self.xyz_groupbox)
        self.x_px_spinbox.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.x_px_spinbox.setDecimals(4)
        self.x_px_spinbox.setObjectName("x_px_spinbox")
        self.x_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.x_px_spinbox)
        self.groupbox_vbox.addLayout(self.x_form)
        self.y_form = QtWidgets.QFormLayout()
        self.y_form.setObjectName("y_form")
        self.y_px_label = QtWidgets.QLabel(self.xyz_groupbox)
        self.y_px_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";")
        self.y_px_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.y_px_label.setObjectName("y_px_label")
        self.y_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.y_px_label)
        self.y_px_spinbox = QtWidgets.QDoubleSpinBox(self.xyz_groupbox)
        self.y_px_spinbox.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.y_px_spinbox.setDecimals(4)
        self.y_px_spinbox.setObjectName("y_px_spinbox")
        self.y_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.y_px_spinbox)
        self.groupbox_vbox.addLayout(self.y_form)
        self.z_form = QtWidgets.QFormLayout()
        self.z_form.setObjectName("z_form")
        self.z_px_label = QtWidgets.QLabel(self.xyz_groupbox)
        self.z_px_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"Arial\";")
        self.z_px_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.z_px_label.setObjectName("z_px_label")
        self.z_form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.z_px_label)
        self.z_px_spinbox = QtWidgets.QDoubleSpinBox(self.xyz_groupbox)
        self.z_px_spinbox.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.z_px_spinbox.setDecimals(4)
        self.z_px_spinbox.setObjectName("z_px_spinbox")
        self.z_form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.z_px_spinbox)
        self.groupbox_vbox.addLayout(self.z_form)
        self.xyz_groupbox_hbox.addLayout(self.groupbox_vbox)
        self.xyz_vbox.addWidget(self.xyz_groupbox)
        self.sure_button = QtWidgets.QPushButton(xyz_px_dialog)
        self.sure_button.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.sure_button.setObjectName("sure_button")
        self.xyz_vbox.addWidget(self.sure_button)
        self.xyz_px_dialog_hbox.addLayout(self.xyz_vbox)

        self.retranslateUi(xyz_px_dialog)
        QtCore.QMetaObject.connectSlotsByName(xyz_px_dialog)

    def retranslateUi(self, xyz_px_dialog):
        _translate = QtCore.QCoreApplication.translate
        xyz_px_dialog.setWindowTitle(_translate("xyz_px_dialog", "XYZ Size"))
        self.x_px_label.setText(_translate("xyz_px_dialog", " X:"))
        self.y_px_label.setText(_translate("xyz_px_dialog", " Y:"))
        self.z_px_label.setText(_translate("xyz_px_dialog", " Z:"))
        self.sure_button.setText(_translate("xyz_px_dialog", "OK"))
