# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_create_chart.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(861, 542)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(25, 35, 45);\n"
"font: 9pt \"Microsoft YaHei\";")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QHBoxLayout()
        self.main_layout.setContentsMargins(6, 6, 6, 6)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.control_panel = QtWidgets.QWidget(self.centralwidget)
        self.control_panel.setMaximumSize(QtCore.QSize(240, 16777215))
        self.control_panel.setObjectName("control_panel")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.control_panel)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.control_layout = QtWidgets.QVBoxLayout()
        self.control_layout.setObjectName("control_layout")
        self.file_group = QtWidgets.QGroupBox(self.control_panel)
        self.file_group.setStyleSheet("QGroupBox#file_group\n"
"{\n"
"    border: 1px solid rgb(70,80,100);\n"
"    margin-top: 3.0ex;\n"
"}\n"
"QGroupBox#file_group::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.file_group.setObjectName("file_group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.file_group)
        self.verticalLayout_4.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.file_layout = QtWidgets.QVBoxLayout()
        self.file_layout.setContentsMargins(10, 6, 10, 6)
        self.file_layout.setSpacing(6)
        self.file_layout.setObjectName("file_layout")
        self.load_btn = QtWidgets.QPushButton(self.file_group)
        self.load_btn.setObjectName("load_btn")
        self.file_layout.addWidget(self.load_btn)
        self.file_label = QtWidgets.QLabel(self.file_group)
        self.file_label.setObjectName("file_label")
        self.file_layout.addWidget(self.file_label)
        self.verticalLayout_4.addLayout(self.file_layout)
        self.control_layout.addWidget(self.file_group)
        self.var_group = QtWidgets.QGroupBox(self.control_panel)
        self.var_group.setStyleSheet("QGroupBox#var_group\n"
"{\n"
"    border: 1px solid rgb(70,80,100);\n"
"    margin-top: 3.0ex;\n"
"}\n"
"QGroupBox#var_group::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.var_group.setObjectName("var_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.var_group)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.var_layout = QtWidgets.QVBoxLayout()
        self.var_layout.setContentsMargins(10, 6, 10, 6)
        self.var_layout.setSpacing(6)
        self.var_layout.setObjectName("var_layout")
        self.var_label = QtWidgets.QLabel(self.var_group)
        self.var_label.setObjectName("var_label")
        self.var_layout.addWidget(self.var_label)
        self.var_combo = QtWidgets.QComboBox(self.var_group)
        self.var_combo.setObjectName("var_combo")
        self.var_layout.addWidget(self.var_combo)
        self.group_check = QtWidgets.QCheckBox(self.var_group)
        self.group_check.setObjectName("group_check")
        self.var_layout.addWidget(self.group_check)
        self.verticalLayout_2.addLayout(self.var_layout)
        self.control_layout.addWidget(self.var_group)
        self.plot_group = QtWidgets.QGroupBox(self.control_panel)
        self.plot_group.setStyleSheet("QGroupBox#plot_group\n"
"{\n"
"    border: 1px solid rgb(70,80,100);\n"
"    margin-top: 3.0ex;\n"
"}\n"
"QGroupBox#plot_group::title\n"
"{\n"
"    subcontrol-origin:margin;\n"
"    left: 10px;\n"
"}")
        self.plot_group.setObjectName("plot_group")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.plot_group)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.plot_layout = QtWidgets.QVBoxLayout()
        self.plot_layout.setContentsMargins(10, 6, 10, 6)
        self.plot_layout.setSpacing(6)
        self.plot_layout.setObjectName("plot_layout")
        self.hist_radio = QtWidgets.QRadioButton(self.plot_group)
        self.hist_radio.setChecked(True)
        self.hist_radio.setObjectName("hist_radio")
        self.plot_layout.addWidget(self.hist_radio)
        self.box_radio = QtWidgets.QRadioButton(self.plot_group)
        self.box_radio.setObjectName("box_radio")
        self.plot_layout.addWidget(self.box_radio)
        self.verticalLayout_6.addLayout(self.plot_layout)
        self.control_layout.addWidget(self.plot_group)
        self.refresh_btn = QtWidgets.QPushButton(self.control_panel)
        self.refresh_btn.setObjectName("refresh_btn")
        self.control_layout.addWidget(self.refresh_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.control_layout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.control_layout)
        self.main_layout.addWidget(self.control_panel)
        self.analyze_view = QtWidgets.QWidget(self.centralwidget)
        self.analyze_view.setObjectName("analyze_view")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.analyze_view)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.analyze_view_layout = QtWidgets.QVBoxLayout()
        self.analyze_view_layout.setObjectName("analyze_view_layout")
        self.verticalLayout_7.addLayout(self.analyze_view_layout)
        self.main_layout.addWidget(self.analyze_view)
        self.verticalLayout.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 861, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3D Dataset Statistical Analysis Tool"))
        self.file_group.setTitle(_translate("MainWindow", "Data File"))
        self.load_btn.setText(_translate("MainWindow", "Load Excel File"))
        self.file_label.setText(_translate("MainWindow", "No file loaded"))
        self.var_group.setTitle(_translate("MainWindow", "Variable Selection"))
        self.var_label.setText(_translate("MainWindow", "Select numeric column:"))
        self.group_check.setText(_translate("MainWindow", "Group by (Group column)"))
        self.plot_group.setTitle(_translate("MainWindow", "Plot Type"))
        self.hist_radio.setText(_translate("MainWindow", "Histogram"))
        self.box_radio.setText(_translate("MainWindow", "Box Plot"))
        self.refresh_btn.setText(_translate("MainWindow", "Refresh Analysis"))
