# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_filter_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_filter_dialog(object):
    def setupUi_filter(self, filter_dialog):
        filter_dialog.setObjectName("filter_dialog")
        filter_dialog.resize(508, 142)
        filter_dialog.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"微软雅黑\";\n"
"background-color: rgb(25, 35, 45);")
        self.verticalLayout = QtWidgets.QVBoxLayout(filter_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_path_grid = QtWidgets.QGridLayout()
        self.select_path_grid.setContentsMargins(9, 9, 9, 9)
        self.select_path_grid.setVerticalSpacing(18)
        self.select_path_grid.setObjectName("select_path_grid")
        self.save_label = QtWidgets.QLabel(filter_dialog)
        self.save_label.setObjectName("save_label")
        self.select_path_grid.addWidget(self.save_label, 0, 0, 1, 1)
        self.save_path_open_button = QtWidgets.QPushButton(filter_dialog)
        self.save_path_open_button.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.save_path_open_button.setObjectName("save_path_open_button")
        self.select_path_grid.addWidget(self.save_path_open_button, 0, 2, 1, 1)
        self.save_lineEdit = QtWidgets.QLineEdit(filter_dialog)
        self.save_lineEdit.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.save_lineEdit.setObjectName("save_lineEdit")
        self.select_path_grid.addWidget(self.save_lineEdit, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.select_path_grid)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.select_button_hbox = QtWidgets.QHBoxLayout()
        self.select_button_hbox.setContentsMargins(9, 9, 9, 9)
        self.select_button_hbox.setObjectName("select_button_hbox")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.select_button_hbox.addItem(spacerItem1)
        self.filter_ok_button = QtWidgets.QPushButton(filter_dialog)
        self.filter_ok_button.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.filter_ok_button.setObjectName("filter_ok_button")
        self.select_button_hbox.addWidget(self.filter_ok_button)
        self.filter_cancel_button = QtWidgets.QPushButton(filter_dialog)
        self.filter_cancel_button.setStyleSheet("background-color: rgb(25, 35, 45);")
        self.filter_cancel_button.setObjectName("filter_cancel_button")
        self.select_button_hbox.addWidget(self.filter_cancel_button)
        self.verticalLayout.addLayout(self.select_button_hbox)

        self.retranslateUi_filter(filter_dialog)
        QtCore.QMetaObject.connectSlotsByName(filter_dialog)

    def retranslateUi_filter(self, filter_dialog):
        _translate = QtCore.QCoreApplication.translate
        filter_dialog.setWindowTitle(_translate("filter_dialog", "Select Path"))
        self.save_label.setText(_translate("filter_dialog", "Filter save path:"))
        self.save_path_open_button.setText(_translate("filter_dialog", "Open"))
        self.filter_ok_button.setText(_translate("filter_dialog", "OK"))
        self.filter_cancel_button.setText(_translate("filter_dialog", "Cancel"))
